---
# tasks file for apigee-opdk-iptables-port-block
- name: Using iptables to block a port
  shell: "iptables -A input -p tcp --destination-port {{ destination_port }} ! -s {{ local_address }} -i eth0"
