---
# tasks file for apigee-opdk-iptables-port-block
- name: Using iptables to block a port
  shell: "iptables -A INPUT -p tcp --destination-port {{ destination_port }} ! -s `hostname` -i eth0 -j DROP"
